version: '3'

services:
  back-end-server:
    build: server/
    depends_on:
      - 'database'
    ports: 
      - '3001:3001'

  front-end-server:
    build: front-end/
    depends_on:
      - 'database'
    ports:
      - '3000:3000'

  database:
    build: server/database/
    ports:
      - '5432:5432'
